# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9324b0a1114b56808185dd31b3a2928815d2d4729a8947d4cec5a194bc51a8d779eeeb31436f979d79172cad912a01ac7998f37de91c042a941829d931b6b641

test:
  secret_key_base: ad020dbcf3b6ac035fca324783888eaf9ae99c0ab179b5d385d2c2072c0417b35f6d4e77f7bf3f2a88b84a95a81ee6aa31fe18ffbecaf8aec5636d63cbcece98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
